# important features for the pictures
dataset: fungi
attributes: fungi
cluster_feature_method: linear # [kmeans, random, linear]
model_type: clip
model_size: ViT-B/32
mahalanobis: True
division_power: 2
linear_epochs: 50 
reinit: True # True/False
num_attributes: 64 # [16, 32, 64, 128, 256, 512]
seed: 1

# optimization parameters
lr: 0.001
batch_size: 4 #28
epochs: 125

# model structure
linear_model: [linear, linear] 
score_model: [linear]

json_file: "/export/home/xyang/hiwi/LM4CV_similarity/data/fungi/split_zhou_Fungi.json" #100 samples per class for testing;100 samples per class for training
ROOT: "/export/compvis-nfs/group/datasets/microbiology_big/images_png" #image path

use_patches: False # [True, False]whether use patches or not
IMP_SAMP_fix: True # [True, False]when use patches,whether use the fix patches method
n_crops_per_image: 7 # number of crops per image

use_voting: False

base_ratio: 0.4 # the ratio of the base train class, when base_ratio=0.5, the ratio of the novel class is 0.5. when base_ratio=1.0, the ratio of the novel class is 0.0
base_ratio_seed: 42 #Change this seed to get different base/novel combinations.
use_few_shot: False #whether use few shot learning or not, for 10-shot


evaluate_with_novel_classes: False #whether evaluate only with novel classes or with whole classes
with_attributes: True #based on the attributes or not
umap: True #generate umap or not

without_zscore: True #umap generated without generization
with_zscore: True #umap generated without generization
testing_samples_per_class: 100 # the number of testing samples per class, determined by 'split_zhou_Fungi.json'


attribute_similarity_scores: True #Whether to calculate the similarity of each attribute to the class or not.


knn-classifier: True #whether use knn classifier or not
