# important features for the pictures
dataset: fungi
attributes: fungi
cluster_feature_method: linear # [kmeans, random, linear]
model_type: clip
model_size: ViT-B/32
mahalanobis: True
division_power: 2
linear_epochs: 50 #50
reinit: False # True/False
num_attributes: 4 # [16, 32, 64, 128, 256, 512]
seed: 1

# optimization parameters
lr: 0.001
batch_size: 4 #28
epochs: 125

# model structure
linear_model: [linear, linear] 
score_model: [linear]

json_file: "/export/home/ra79nod/proj/LM4CV_similarity/data/fungi/split_zhou_Fungi.json"
ROOT: "/export/group/datasets/microbiology/images_png"

use_voting: False

with_attributes: True
evaluate_with_novel_classes: False

IMP_SAMP_fix: True
use_patches: True
n_crops_per_image: 7
use_few_shot: False
umap: True
